typography_spectrum: 0.3058112426660955
content_rating:
  adult: false
color:
  brandStrength: 0.776126780314371
  lightness: 0.582668190356344
  saturation: 0.5167156669776887
  rhythmicContrast: 0.4122892946470529
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.6434958635363728
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/97f9b744-7c40-414b-864c-7a42f2da3ef5.jpg
name: Red Moon Solutions
navigation:
  - name: 'Precious cargo: the Container Artist Residency program sets sail.'
    id: b323e241-0b22-4331-9f8b-7752c684ba74
    type: content
title: Prepare to be boarded!
description: 'Create, Cosplay, Conquer'
